/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Asus
 */
public class AdminCRUDCarGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminCRUDCarGUI
     */
    public AdminCRUDCarGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabelListMobil = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtBack = new javax.swing.JButton();
        TxPricePHours = new javax.swing.JTextField();
        BtEdit = new javax.swing.JButton();
        BtDelete1 = new javax.swing.JButton();
        BtCreate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxCarName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelListMobil.setViewportView(jTable1);

        getContentPane().add(TabelListMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 480, 120));

        BtBack.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtBack.setText("Back");
        BtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 90, -1));

        TxPricePHours.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxPricePHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPricePHoursActionPerformed(evt);
            }
        });
        getContentPane().add(TxPricePHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 140, -1));

        BtEdit.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtEdit.setText("Edit");
        BtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditActionPerformed(evt);
            }
        });
        getContentPane().add(BtEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 90, -1));

        BtDelete1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtDelete1.setText("Delete");
        BtDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 90, -1));

        BtCreate.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        BtCreate.setText("Create");
        BtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCreateActionPerformed(evt);
            }
        });
        getContentPane().add(BtCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Price per Hour");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Car Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        TxCarName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCarNameActionPerformed(evt);
            }
        });
        getContentPane().add(TxCarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 140, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Car Data");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RentCarPro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AdminCrud.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCarNameActionPerformed

    private void TxPricePHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPricePHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPricePHoursActionPerformed

    private void BtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtCreateActionPerformed

    private void BtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtBackActionPerformed

    private void BtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtEditActionPerformed

    private void BtDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtDelete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCRUDCarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCRUDCarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCRUDCarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCRUDCarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCRUDCarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBack;
    private javax.swing.JButton BtCreate;
    private javax.swing.JButton BtDelete1;
    private javax.swing.JButton BtEdit;
    private javax.swing.JScrollPane TabelListMobil;
    private javax.swing.JTextField TxCarName;
    private javax.swing.JTextField TxPricePHours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
