/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Asus
 */
public class TransaksiMobilGUI extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiMobilGUI
     */
    public TransaksiMobilGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtListCars = new javax.swing.JButton();
        BtConfirm = new javax.swing.JButton();
        TxHours = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Cbidmobil = new javax.swing.JComboBox<>();
        TxCarName = new javax.swing.JTextField();
        TxPricePHours = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TabelListMobil = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtListCars.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtListCars.setText("List Car");
        BtListCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtListCarsActionPerformed(evt);
            }
        });
        getContentPane().add(BtListCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 120, -1));

        BtConfirm.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        BtConfirm.setText("Confirm");
        BtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(BtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 120, -1));

        TxHours.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxHoursActionPerformed(evt);
            }
        });
        getContentPane().add(TxHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 140, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Price per Hour");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Hours");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID Car");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        Cbidmobil.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Cbidmobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Cbidmobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 140, 20));

        TxCarName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCarNameActionPerformed(evt);
            }
        });
        getContentPane().add(TxCarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 140, -1));

        TxPricePHours.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TxPricePHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPricePHoursActionPerformed(evt);
            }
        });
        getContentPane().add(TxPricePHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 140, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Car Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Rent Car");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RentCarPro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gui trans mobil.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelListMobil.setViewportView(jTable1);

        getContentPane().add(TabelListMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 620, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxHoursActionPerformed

    private void BtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtConfirmActionPerformed

    private void BtListCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtListCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtListCarsActionPerformed

    private void TxCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCarNameActionPerformed

    private void TxPricePHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPricePHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPricePHoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiMobilGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiMobilGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiMobilGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiMobilGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiMobilGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConfirm;
    private javax.swing.JButton BtListCars;
    private javax.swing.JComboBox<String> Cbidmobil;
    private javax.swing.JScrollPane TabelListMobil;
    private javax.swing.JTextField TxCarName;
    private javax.swing.JTextField TxHours;
    private javax.swing.JTextField TxPricePHours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
